const Products = [
  {
    id: "1",
    name: "K-Swiss V8 - Masculino",
    image: "/assets/SpatatoK-swiss.png",
    price: 200,
    priceDiscount: 149.9,
    reference: "URB0001",
    stars: 4.5,
    rating: 123,
    description: "Sapato K-Swiss. Moderno e estiloso.",
    images: [
      { src: "/assets/SpatatoK-swiss.png" },
      { src: "/assets/SpatatoK-swiss.png" },
    ],
    colors: ["#ffffff", "#000000"],
    brand: "K-Swiss",
    gender: "Masculino",
    condition: "Novo",
  },
  {
    id: "2",
    name: "Nike Air Max - Feminino",
    image: "/assets/AirMax.png",
    price: 350,
    priceDiscount: 299.9,
    reference: "URB0002",
    stars: 4.8,
    rating: 254,
    description: "Tênis Nike Air Max. Conforto e estilo.",
    images: [
      { src: "/assets/AirMax.png" },
      { src: "/assets/AirMax.png" },
    ],
    colors: ["#ffffff", "#ff0000"],
    brand: "Nike",
    category: "Casual",
    gender: "Feminino",
    condition: "Novo",
  },
  {
    id: "3",
    name: "Adidas UltraBoost - Unissex",
    image: "/assets/Ultraboost.png",
    price: 400,
    priceDiscount: 350,
    reference: "URB0003",
    stars: 4.9,
    rating: 310,
    description: "Adidas UltraBoost. Performance e conforto.",
    images: [
      { src: "/assets/Ultraboost.png" },
      { src: "/assets/Ultraboost.png" },
    ],
    colors: ["#000000", "#888888"],
    brand: "Adidas",
    category : "Corrida",
    gender: "Unissex",
    condition: "Usado",
  },
  {
    id: "4",
    name: "Air Jordan - Collector Edition",
    image: "/assets/AirJordanCollector.png",
    price: 320,
    priceDiscount: 270,
    reference: "URB0004",
    stars: 4.7,
    rating: 198,
    description: "Air Jordan, feito para aqueles que merecem.",
    images: [
      { src: "/assets/AirJordanCollector.png" },
      { src: "/assets/AirJordanCollector.png" },
    ],
    colors: ["#00ff00", "#000000"],
    brand: "Puma",
    category: "Utilitário", 
    gender: "Masculino",
    condition: "Novo",
  },
  {
    id: "5",
    name: "Nike Air Max - Masculino",
    image: "/assets/SneakerBranco.png",
    price: 1500,
    priceDiscount: 1300,
    reference: "URB0005",
    stars: 5.0,
    rating: 50,
    description: "Balenciaga Triple S. Luxo e sofisticação.",
    images: [
      { src: "/assets/SneakerBranco.png" },
      { src: "/assets/SneakerBranco.png" },
    ],
    colors: ["#ffff00", "#0000ff"],
    brand: "Nike",
    category: "Esporte e lazer",
    gender: "Masculino",
    condition: "Usado",
  },
];

export default Products;
